services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: aerotech_db
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  api:
    build:
      context: ./backend
      dockerfile: ../docker/Dockerfile.backend
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql+asyncpg://user:password@db:5432/aerotech_db
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - db
      - redis

  web:
    build:
      context: ./frontend
      dockerfile: ../docker/Dockerfile.frontend
    command: npm run dev -- --hostname 0.0.0.0 --port 3000
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    ports:
      - "3000:3000"
    depends_on:
      - api

  worker:
    build:
      context: ./backend
      dockerfile: ../docker/Dockerfile.backend
    command: celery -A app.worker worker --loglevel=info
    depends_on:
      - redis
      - db
    volumes:
      - ./backend:/app
    environment:
      - DATABASE_URL=postgresql+asyncpg://user:password@db:5432/aerotech_db
      - REDIS_URL=redis://redis:6379/0